# Configuration for Arch Install Script

# Installation Mode - set to "yes" or "no" for unattended installation
UNATTENDED="no"

# System Configuration
TIME_ZONE="Asia/Kuala_Lumpur"
HOST_NAME="arch"
USER_NAME="black"
ROOT_PASS="pass"
USER_PASS="pass"

# Disk Configuration
DISK="/dev/sda"
BOOT_SIZE="512M"
ROOT_SIZE=""

# Microcode package - set to "intel-ucode", "amd-ucode", or leave empty if not needed
MICROCODE_PKG="intel-ucode"